# Generated by Django 3.2 on 2021-04-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
