# Generated by Django 3.2.4 on 2021-07-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210716_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='address',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
