# Generated by Django 3.2 on 2021-05-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_name', models.CharField(max_length=20, unique=True)),
                ('pair_vol', models.FloatField(max_length=18)),
                ('coin_price', models.FloatField(max_length=18)),
            ],
        ),
    ]
