# Generated by Django 3.2.4 on 2021-06-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_coinpair_pair_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinpair',
            name='pair_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
