# Generated by Django 3.2.4 on 2021-06-30 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_coinpair_pair_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=500)),
                ('available_bal', models.IntegerField()),
                ('locked_bal', models.IntegerField()),
                ('total_bal', models.IntegerField()),
                ('usdt_bal', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
