# Generated by Django 3.2.4 on 2021-06-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_currency_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_wallet',
            name='wallet_address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
