# Generated by Django 3.2.4 on 2021-07-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_currency_wallet_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_wallet',
            name='coin_pair',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.coinpair'),
            preserve_default=False,
        ),
    ]
