# Generated by Django 3.2.4 on 2021-07-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_currency_wallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateTimeField(auto_now_add=True)),
                ('user_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency_wallet')),
            ],
        ),
    ]
