# Generated by Django 3.2.4 on 2021-08-17 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_wallet_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2p_Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_sell_price', models.FloatField()),
                ('sell_volume', models.FloatField()),
                ('sell_date', models.DateTimeField(auto_now_add=True)),
                ('user_cid_name', models.CharField(max_length=20)),
                ('coin_placer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
