# Generated by Django 3.2.4 on 2021-08-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_p2p_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2p_seller',
            name='sell_total_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
