# Generated by Django 3.2.4 on 2021-08-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_p2p_seller_sell_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2p_seller',
            name='user_cid_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
