# Generated by Django 3.2.4 on 2021-08-21 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_p2p_seller_sell_pair_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2p_Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_pair_name', models.CharField(max_length=50)),
                ('unit_buy_price', models.FloatField()),
                ('buy_volume', models.FloatField()),
                ('buy_total_price', models.FloatField()),
                ('buy_date', models.DateTimeField(auto_now_add=True)),
                ('buyer_cid_name', models.CharField(blank=True, max_length=20)),
                ('coin_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
