# Generated by Django 3.2.4 on 2021-07-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_qrcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_qrcode',
            old_name='qrcode',
            new_name='qr_code',
        ),
    ]
