# Generated by Django 3.2.4 on 2021-07-16 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_rename_qrcode_user_qrcode_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('SSN', 'SSN'), ('PASSPORT', 'PASSPORT'), ('DRIVING_LICENCE', 'DRIVING_LICENCE')], default='SSN', max_length=20)),
                ('id_number', models.IntegerField()),
                ('doc_front_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('doc_back_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('doc_selfie', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
