# Generated by Django 3.2.4 on 2021-07-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_kyc',
            name='document_type',
            field=models.CharField(choices=[('SSN', 'SSN'), ('PASSPORT', 'PASSPORT'), ('DRIVING_LICENSE', 'DRIVING_LICENSE')], default='SSN', max_length=20),
        ),
    ]
